name: test on push to main

env:
  REPO_NAME: panubo/staticsite

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.7.0

      - name: Build
        run:
          make build

      - name: Test
        run:
          make test
